apiVersion: policies.kubewarden.io/v1
kind: AdmissionPolicy
metadata:
  name: psp-user-group
  namespace: default
spec:
  policyServer: default
  module: registry://ghcr.io/kubewarden/tests/user-group-psp:v0.4.7
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations:
        - CREATE
        - UPDATE
  mutating: true
  settings:
    run_as_user:
      rule: "MustRunAs"
      ranges:
        - min: 1000
          max: 2000
        - min: 3000
          max: 4000
    run_as_group:
      rule: "RunAsAny"
    supplemental_groups:
      rule: "RunAsAny"
